DROP TABLE payments CASCADE CONSTRAINTS;
DROP TABLE ReminderSettings CASCADE CONSTRAINTS;
DROP TABLE bills CASCADE CONSTRAINTS;
DROP TABLE users;

DROP TABLE user_roles CASCADE CONSTRAINTS;
DROP TABLE roles;
DROP TABLE BillCategory;